services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=ReelReviews
      - POSTGRES_PASSWORD=${REELREVIEWS_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DATABASE_URL=postgres://ReelReviews:${REELREVIEWS_DATABASE_PASSWORD}@db:5432/ReelReviews_production
    volumes:
      - .:/app

volumes:
  dbdata: